spring.application.name=Library

spring.datasource.url=jdbc:postgresql://localhost:5432/library?currentSchema=library
spring.jpa.properties.hibernate.default_schema=library
spring.datasource.username=library_root
spring.datasource.password=123123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
